ExemplosWebPython/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('contatos/', include('contatos.urls')), #chaque url contenant contatos/ vai para contatos.urls
]

contatos/urls.py
from django.urls.conf import path
from contatos import views

app_name = "contatos"

urlpatterns = [
    path('cria/', views.ContatoCreateView.as_view(), 
        name='cria-contato'),
    path('lista/', views.ContatoListView.as_view(), 
        name='lista-contatos'),
    path('', views.ContatoListView.as_view(), 
        name='home-contatos'),
]

contatos/models.py
from django.db import models

# Create your models here.

class Pessoa(models.Model):
    nome = models.CharField(
    max_length=100, help_text='Entre o nome')
    idade = models.IntegerField(
    help_text='Entre a idade')
    salario = models.DecimalField(
    help_text='Entre o salário', 
    decimal_places=2, max_digits=8)
    email = models.EmailField(
    help_text='Informe o email', max_length=254)
    telefone = models.CharField(
    help_text='Telefone com DDD e DDI', max_length=20)
    dtNasc = models.DateField(
    help_text='Nascimento no formato DD/MM/AAAA', 
    verbose_name='Data de nascimento')
    
    def __str__(self): # it's the to string of java
        return self.nome

contatos/forms.py
from django import forms
from contatos.models import Pessoa

class ContatoModel2Form(forms.ModelForm):
    dtNasc = forms.DateField(
    input_formats=['%d/%m/%Y'], 
    label='Data do nascimento',
    help_text='Nascimento no formato DD/MM/AAAA',
    )

    class Meta:
        model = Pessoa
        fields = '__all__'

contatos/views.py
from django.shortcuts import render
from contatos.models import Pessoa
from django.views.generic.base import View
from contatos.forms import ContatoModel2Form

# Create your views here.
class ContatoListView(View):
 def get(self, request, *args, **kwargs):
    pessoas = Pessoa.objects.all()
    context = { 'pessoas': pessoas, }
    return render(request, 'contatos/listaContatos.html', context)

class ContatoCreateView(View):
   def get(self, request, *args, **kwargs):
      contexto = { 'formulario': ContatoModel2Form, }
      return render(request, "contatos/criaContato.html", contexto)
 
   def post(self, request, *args, **kwargs):
      formulario = ContatoModel2Form(request.POST)
      if formulario.is_valid():
         contato = formulario.save()
         contato.save()
         return HttpResponseRedirect(reverse_lazy(
         "contatos:lista-contatos"))    

contatos/templates/contatos/criaContato.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="" method="post" class="formulario"></form>
        <table>
        {{ formulario.as_ul }}
        </table>
</body>
</html>

contatos/templates/contatos/links.html
<!--
Para incluir esse fragmento de página HTML
em uma página HTML use:
{ % include 'contatos/links.html' % }
-->
<a href="/">
    Home-Page
    </a> |
    <a href="{% url 'contatos:home-contatos' %}">
    Página inicial
    </a> |
    <a href="{% url 'contatos:lista-contatos' %}">
    Listar contatos
    </a> |
    <a href="{% url 'contatos:cria-contato' %}">
    Cadastrar contato
    </a>      
    <hr>
    

contatos/templates/contatos/listaContatos.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Lista Contatos</title>
<link rel="stylesheet" href="{% static 'contatos/css/estilo.css' %}">
</head>
<body>
 {% include 'contatos/links.html' %}
 <h1>Lista de Contatos</h1>
 <h6>listaContatos.html</h6>
 <table>
 <tr><th>Nome</th><th>Idade</th><th>Salário</th><th>Ações disponíveis</th></tr>
 {% for pessoa in pessoas %}
 <tr>
 <td>{{ pessoa.nome }}</td><td>{{pessoa.idade }}</td><td>{{ pessoa.salario }}</td>
 <td><a href="{% url 'contatos:atualiza-contato' pk=pessoa.id %}">Atualizar</a> | 
 <a href="{% url 'contatos:apaga-contato' pk=pessoa.id %}">Excluir</a></td>
 </tr>
 {% empty %}
 <tr><th colspan="5">Ainda não tem contatos cadastrados</th></tr>
 {% endfor %}
 </table>
</body>
</html>